apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
  namespace: default
  labels:
    app: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      serviceAccountName: portfolio-sa
      containers:
      - name: portfolio
        image: satwikkulshrestha/frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://portfolio-backend-service:5001"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
